# Generated by Django 2.2.3 on 2020-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
